name: neom_downloads
description: Downloads functionalities for Open Neom
version: 1.1.0
homepage: https://github.com/Open-Neom/neom_downloads
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Cyberneom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
